spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/carshop
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher